### ISSUE TITLE
error running pyRINEX

### ISSUE THREAD

**Issue by DfAC** [scivision/pyrinex#12]
Hi, 
I am running python 3.6.4. I got error running a GPS RINEX 2.11 navigation file
````
plots.py, line 28, in plotobs
    if not p in obs:
TypeError: argument of type 'NoneType' is not iterable
````

Have you seen this error before? Am I missing a library?

**Comment by scivision** [comment]
I think it's a typo bug, when one only reads a NAV file. I believe it is fixed by https://github.com/scivision/pyrinex/commit/05f3d01b5e267bdf040d7fac3c62c496cc029344
