### ISSUE TITLE
cast to int an unicode variable

### ISSUE THREAD

**Issue by Cami23** [scivision/pyrinex#6]
This codeline, i can't compile in Python 2.7 

sv.append(int(l[:2]))

What can i do?

**Comment by scivision** [comment]
What error is it giving?
This program is automatically tested in Python 2.7/3.6
https://travis-ci.org/scivision/pyrinex

**Comment by Cami23** [comment]
The error is in this codeline: sv.append(int(l[:2]))
This string contains a empty place, so it's impossible the cast to int. I'm trying to use a function to eliminate the empty place, however i dont know if it's functional

**Comment by scivision** [comment]
OK this is a Python 2 specific problem I think, as in Python 3, int('      8      ') == 8

**Comment by Cami23** [comment]
You're right! 
It's compatible with Python3

**Comment by scivision** [comment]
@Cami23 it should work in both Py 2.7 and 3 now
