### ISSUE TITLE
The time for gps.getSatXYZ(nav,1,arr) function

### ISSUE THREAD

**Issue by weisongwen** [scivision/pyrinex#9]
Hi @scivision  Thanks for your effort in this package.
when I use following function, I found that the output satellite position is not right. Because if I use the output satellite position to calculate the gps receiver's position,  gps receiver's position is wrong.
```
satpos1 = gps.getSatXYZ(nav,1,arr)
satpos2 = gps.getSatXYZ(nav,2,arr)
satpos3 = gps.getSatXYZ(nav,3,arr)
```
the parameter **arr** in function **gps.getSatXYZ** is the UTC time from .obs file? I use the following code to get the time for function **gps.getSatXYZ**.
```
arr_test = np.array([gps_receiver_time + datetime.timedelta(minutes=i) for i in range(2)])#make sure the length of arr_test is not 0

```
**gps_receiver_time** is the UTC time provided by .obs file.

and then compute satellite 3 position:
```
satellite_position=gps.getSatXYZ(nav,3,arr_test)
```
do you have any idea about this issue?

Best 
Welson

**Comment by scivision** [comment]
I don't think there's a `getSatXYZ` in this package?

**Comment by weisongwen** [comment]
Hi， @scivision  sorry for this mistake.
the function```satellite_position=gps.getSatXYZ(nav,3,arr_test)``` is acquired from another package, sorry for this .

Best 
Welson
